/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  SubCategory as PrismaSubCategory,
  Category as PrismaCategory,
} from "@prisma/client";

export class SubCategoryServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.SubCategoryCountArgs, "select">
  ): Promise<number> {
    return this.prisma.subCategory.count(args);
  }

  async subCategories(
    args: Prisma.SubCategoryFindManyArgs
  ): Promise<PrismaSubCategory[]> {
    return this.prisma.subCategory.findMany(args);
  }
  async subCategory(
    args: Prisma.SubCategoryFindUniqueArgs
  ): Promise<PrismaSubCategory | null> {
    return this.prisma.subCategory.findUnique(args);
  }
  async createSubCategory(
    args: Prisma.SubCategoryCreateArgs
  ): Promise<PrismaSubCategory> {
    return this.prisma.subCategory.create(args);
  }
  async updateSubCategory(
    args: Prisma.SubCategoryUpdateArgs
  ): Promise<PrismaSubCategory> {
    return this.prisma.subCategory.update(args);
  }
  async deleteSubCategory(
    args: Prisma.SubCategoryDeleteArgs
  ): Promise<PrismaSubCategory> {
    return this.prisma.subCategory.delete(args);
  }

  async getCategory(parentId: string): Promise<PrismaCategory | null> {
    return this.prisma.subCategory
      .findUnique({
        where: { id: parentId },
      })
      .category();
  }
}
